import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Navbar from "./_components/navbar";
import MobileFooter from "@/components/ui/mobile-footer";
import Sidebar from "./_components/account-sidebar";
// import { db } from "@/lib/db";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const users = await db.user.find();

  // console.log(users);

  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
          <div className="pb-24 lg:pb-2 overflow-hidden">
            <Navbar />
            <Sidebar />
            {children}
            {/* </ThemeProvider> */}
          </div>
          <MobileFooter />
        </body>
      </html>
    </SessionProvider>
  );
}
